# Generated by Django 2.1.5 on 2019-01-27 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideService', '0002_auto_20190127_0343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
