# Generated by Django 2.1.5 on 2019-01-27 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideService', '0003_auto_20190127_0347'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='email',
            field=models.EmailField(default='ny32@duke.edu', max_length=254),
        ),
        migrations.AlterField(
            model_name='driver',
            name='special_info',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='special_request',
            field=models.TextField(blank=True),
        ),
    ]
