# Generated by Django 2.1.5 on 2019-01-27 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rideService', '0004_auto_20190127_0359'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sharer',
            old_name='user_name',
            new_name='account',
        ),
    ]
