# Generated by Django 2.1.5 on 2019-02-01 15:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

     dependencies = [
          ('rideService', '0007_auto_20190127_0511'),
     ]
     
     operations = [
          migrations.RemoveField(
               model_name='driver',
               name='account',
          ),
          migrations.RemoveField(
               model_name='request',
               name='ride_owner',
          ),
          migrations.RemoveField(
               model_name='sharer',
               name='account',
          ),
          migrations.DeleteModel(
               name='Account',
          ),
          migrations.AddField(
               model_name='driver',
               name='account',
               field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
          ),
          migrations.AddField(
               model_name='request',
               name='ride_owner',
               field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
          ),
          migrations.AddField(
               model_name='sharer',
               name='account',
               field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
          ),
     ]