# Generated by Django 2.1.5 on 2019-02-02 16:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rideService', '0008_auto_20190201_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rideService.Driver'),
        ),
        migrations.AddField(
            model_name='request',
            name='sharer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sharer_request', to=settings.AUTH_USER_MODEL),
        ),
    ]
