# Generated by Django 2.1.5 on 2019-02-02 16:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rideService', '0009_auto_20190202_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='driver',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rideService.Driver'),
        ),
        migrations.AlterField(
            model_name='request',
            name='sharer',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sharer_request', to=settings.AUTH_USER_MODEL),
        ),
    ]
