# Generated by Django 2.1.5 on 2019-02-02 18:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideService', '0011_auto_20190202_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='num_sharer',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)]),
        ),
    ]
