# Generated by Django 2.1.5 on 2019-02-02 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideService', '0012_auto_20190202_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='vehicle_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
